name: Build APK

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: yarn

      - name: install and prebuild
        run: |
          yarn install
          yarn bundle:es
          yarn expo prebuild -p android --clean --no-install

      - name: build apk
        run: ./gradlew assembleDebug
        working-directory: android

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: all-apks-in-one(intermediates)
          retention-days: 5
          path: android/app/build/outputs/apk/debug/*.apk
